export const supplimentSoftSkills = [
    'Accountability',
    'Adaptability',
    'Analytical Thinking',
    'Assertiveness',
    'Communication',
    'Conflict Management',
    'Collaboration',
    'Critical Thinking',
    'Decision Making',
    'Empathy',
    'Feedback Reception',
    'Flexibility',
    'Goal Setting',
    'Innovation',
    'Leadership',
    'Negotiation',
    'Problem Solving',
    'Teamwork',
    'Time Management',
    'Written Communication',
]