import type { AIProvider } from '../../types/template';
// Type-only, so nothing is imported at runtime and the no-side-effects
// rule this module's docstring states still holds.
import type { CredentialKind } from '../../config/providerCatalog';

/**
 * Contracts for the AI transport layer.
 *
 * This module has NO runtime imports beyond a type-only one: no SQLite, no
 * dotenv, no child_process, and no side effects at load. That is what lets the
 * provider tests run hermetically, and a test asserts it.
 */

export type CompletionResponseFormat = 'json' | 'text';

/** The `--effort` levels the Claude CLI accepts. */
export const EFFORT_LEVELS = ['low', 'medium', 'high', 'xhigh', 'max'] as const;
export type EffortLevel = (typeof EFFORT_LEVELS)[number];

export function isEffortLevel(value: unknown): value is EffortLevel {
  return typeof value === 'string' && (EFFORT_LEVELS as readonly string[]).includes(value);
}

/**
 * How much the model may think before answering.
 *
 * `default` leaves the model's own adaptive behaviour alone - which is thinking
 * ON, decided per turn. `off` suppresses it. Depth, when it does think, is
 * `effort`.
 */
export const THINKING_MODES = ['default', 'off'] as const;
export type ThinkingMode = (typeof THINKING_MODES)[number];

export function isThinkingMode(value: unknown): value is ThinkingMode {
  return typeof value === 'string' && (THINKING_MODES as readonly string[]).includes(value);
}

/** A knob a caller asked for that the chosen provider cannot honour. */
export type DroppedParam =
  | 'temperature'
  | 'maxOutputTokens'
  | 'jsonSchema'
  | 'effort'
  | 'thinking';

/**
 * Sampling values the CALLER would like. They are hints, not guarantees:
 * consult `ProviderCapabilities` before assuming one was applied, and read
 * `CompletionResult.droppedParams` afterwards to find out what was not.
 */
export type SamplingHints = {
  readonly maxOutputTokens?: number;
  readonly temperature?: number;
};

/**
 * A wall-clock budget for one completion, shared by every layer that can wait:
 * the concurrency semaphore, the subprocess, and the HTTP retry loops.
 */
export interface Deadline {
  readonly totalMs: number;
  remainingMs(): number;
  expired(): boolean;
}

export function createDeadline(totalMs: number, now: () => number = Date.now): Deadline {
  const startedAt = now();
  const budget = Math.max(1, Math.round(totalMs));
  return {
    totalMs: budget,
    remainingMs() {
      return Math.max(0, budget - (now() - startedAt));
    },
    expired() {
      return now() - startedAt >= budget;
    },
  };
}

export type CompletionRequest = {
  readonly modelName: string;
  /**
   * System text that is byte-stable for a given prompt: the literal preamble
   * before the first `[[variable]]`. Kept separate from the user body because
   * that is the shape the Anthropic API and the CLI's `--system-prompt` both
   * want, and because it keeps per-call data out of the instruction channel.
   */
  readonly stableSystem: string;
  /** System text that varies with the call, e.g. the JSON-only instruction. */
  readonly volatileSystem: string;
  /** The user turn: rendered variables and everything after the first one. */
  readonly userBody: string;
  readonly responseFormat: CompletionResponseFormat;
  /**
   * A JSON Schema the provider may enforce natively.
   *
   * Only set this when the schema is GENERATED BY CODE and the prompt is not
   * one of the admin-editable prompt features. A schema pinned to a prompt an
   * admin can edit turns a recoverable "unparseable text" into a hard
   * transport failure the moment the two drift apart.
   */
  readonly jsonSchema?: Readonly<Record<string, unknown>>;
  readonly sampling: SamplingHints;
  readonly effort?: EffortLevel;
  /** Absent means the provider's own default; see ThinkingMode. */
  readonly thinking?: ThinkingMode;
  readonly deadline: Deadline;
  readonly signal?: AbortSignal;
  /** Stable id of the calling feature, for logs and usage buckets. */
  readonly callSite: string;
};

export type CompletionUsage = {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly cacheReadTokens: number;
  readonly cacheWriteTokens: number;
};

export type CompletionResult = {
  /**
   * The answer. NEVER partial: a turn cut off by the clock or by the model's
   * output limit throws instead of returning what arrived. Returning a
   * fragment is worse than failing here, because `extractJSON` will happily
   * find a balanced sub-object inside a truncated document and hand it to a
   * parser that then blames the prompt.
   */
  readonly text: string;
  readonly resolvedModel: string;
  readonly providerId: AIProvider;
  readonly usage?: CompletionUsage;
  /** Notional on a subscription seat: a measure of work, not an invoice. */
  readonly costUsd?: number;
  readonly droppedParams: readonly DroppedParam[];
  readonly latencyMs: number;
};

export type ProviderCapabilities = {
  readonly id: AIProvider;
  readonly label: string;
  readonly temperature: boolean;
  readonly maxOutputTokens: boolean;
  /** Whether `--effort`, or an equivalent, actually reaches the model. */
  readonly effort: boolean;
  /** Whether the thinking budget can be set at all. */
  readonly thinking: boolean;
  readonly nativeJsonMode: 'response_format' | 'json-schema' | 'none';
  /** false => the facade folds system text into the head of the user body. */
  readonly systemBlocks: boolean;
  readonly requiresApiKey: boolean;
  readonly credentialKind: CredentialKind;
  /** Simultaneous in-flight calls this provider tolerates. */
  readonly maxConcurrency: number;
};

export type ProviderHealth = {
  readonly ok: boolean;
  readonly detail: string;
  readonly checkedAt: string;
  /** Present for the CLI provider: 'oauth_token' means a subscription seat. */
  readonly authMethod?: string | null;
  /** A non-fatal problem an operator should still see (e.g. key-based auth). */
  readonly warning?: string;
  readonly meta?: Readonly<Record<string, unknown>>;
};

export interface AIProviderAdapter {
  readonly id: AIProvider;
  readonly capabilities: ProviderCapabilities;
  /** The model used when neither the prompt nor the caller names one. */
  defaultModelName(): string;
  /** Cheap, cached, never billable, never throws. Boot preflight + admin UI. */
  health(): Promise<ProviderHealth>;
  /** Rejects with AIProviderError - never a bare Error. Honours the deadline. */
  complete(request: CompletionRequest): Promise<CompletionResult>;
}
